#PostgreSQL設定情報
spring:
    datasource:
        url:  jdbc:postgresql://localhost/postgres
        username: postgres
        password: dgic2020
        driverClassName: org.postgresql.Driver

#Mybatis設定情報
mybatis:
    mapper-locations: classpath:sql/*.xml
    config-location: classpath:/mybatis/mybatis-config.xml
